spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

#   ??? ?? ?? schema.sql ?? ?? ? ??? ?????? ??? ? ????
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql